mailserver: ignore vmail user for garbage collection scan
flyingcircusio/fc-nixos pull request #1031
Opened 2024-06-14 13:19 UTC by ctheune

This also introduces the ability to exclude specific users from scanning them for automatic garbage collection roots - which can reduce load drastically.

Re PL-132331

@flyingcircusio/release-managers

## Release process

Impact:

none

Changelog:

- Allow to selectively disable the automatic garbage collection protection scan (fc-userscan) by setting the `flyingcircus.agent.userscan-ignore-users` option. (PL-132331)
- On mailservers we do not scan the "virtual mailbox" user for automatic NixOS garbage collection roots. This will reduce load from our user scan script on those machines, especially with large and/or many mailboxes. (PL-132331)

### PR release workflow (internal)

- [x] PR has internal ticket
- [x] internal issue ID (PL-…) part of branch name
- [x] internal issue ID mentioned in PR description text
- [x] ticket is on Platform agile board
- [x] ticket state set to *Pull request ready*
- [ ] if ticket is more urgent than within the next few days, directly contact a member of the Platform team

## Design notes

- [x] Provide a feature toggle if the change might need to be adjusted/reverted quickly depending on context. Consider whether the default should be `on` or `off`. Example: rate limiting.
- [x] All customer-facing features and (NixOS) options need to be discoverable from documentation. Add or update relevant documentation such that hosted and guided customers can understand it as well.

We're introducing new knobs here: the userscan-ignore-users list can be used to tweak which user are scanned for potential garbage collection roots.

## Security implications

- [x] [Security requirements](https://wiki.flyingcircus.io/System_Development_Guideline#Security_requirement_principles_and_testing) defined? (WHERE)

Mindful use of system resources.

- [x] Security requirements tested? (EVIDENCE)

Manually verified on test33.

2024-06-20 15:35 UTC, osnyx approved these changes

2024-06-20 15:45 UTC, osnyx requested changes
As our documentation covers (fc-)userscan, this deserves to be covered in there as well. https://doc.flyingcircus.io/roles/fc-23.11-production/fc_collect_garbage_userscan.html

2024-06-27 19:13 UTC, dpausp approved these changes

2024-07-04 23:53 UTC, osnyx commented
I'm piggy-backing the doc change for this into another PR.

2024-07-04 23:54 UTC, osnyx approved these changes

2024-07-04 23:54 UTC, merged