varnish: add migration for moving stateDir
flyingcircusio/fc-nixos pull request #1094
Opened 2024-08-29 14:51 UTC by laalsaas

@flyingcircusio/release-managers
PL-132901
## Release process

Impact:

Changelog:

### PR release workflow (internal)

- [x] PR has internal ticket
- [x] internal issue ID (PL-…) part of branch name
- [x] internal issue ID mentioned in PR description text
- [x] ticket is on Platform agile board
- [ ] ticket state set to *Pull request ready*
- [x] if ticket is more urgent than within the next few days, directly contact a member of the Platform team

## Design notes

- [x] Provide a feature toggle if the change might need to be adjusted/reverted quickly depending on context. Consider whether the default should be `on` or `off`. Example: rate limiting.
- [x] All customer-facing features and (NixOS) options need to be discoverable from documentation. Add or update relevant documentation such that hosted and guided customers can understand it as well.

## Security implications

- [x] [Security requirements](https://wiki.flyingcircus.io/System_Development_Guideline#Security_requirement_principles_and_testing) defined? (WHERE)
  - varnish shouldn't crash due to performance issues, this is why the stateDir is moved in the first place
  - however, running instances of varnish should continue to use the old stateDir until the next reboot/service restart
- [x] Security requirements tested? (EVIDENCE)
  - tested changing the stateDir on pntest00, reloading went successfully

2024-08-30 09:21 UTC, ctheune requested changes
We need to coordinate this with @PhilTaken and @Ma27 - we're touching varnish and especially the reload logic, from multiple pointsn ow.

Also, as the stateDir is configurable in the upstream module, I'd like to see this properly managed in upstream, that changes in the stateDir have a proper migration path.

2024-08-30 11:18 UTC, laalsaas commented
> We need to coordinate this with @PhilTaken and @Ma27 - we're touching varnish and especially the reload logic, from multiple points now.

sure, is there a feature branch to have a look at?

> Also, as the stateDir is configurable in the upstream module, I'd like to see this properly managed in upstream, that changes in the stateDir have a proper migration path.

I think this isn't so much of a problem upstream, since upstream doesn't have `reloadOnChange = true` for this unit it just restarts, which means no _reload_ logic is needed, the stateDir should be discarded on restart.

2024-08-30 11:20 UTC, ctheune commented
> I think this isn't so much of a problem upstream, since upstream doesn't have `reloadOnChange = true` for this unit it just restarts, which means no _reload_ logic is needed, the stateDir should be discarded on restart.

Ah, that's good to know. I wonder whether we want to port the reload logic upstream then?

2024-09-04 08:21 UTC, leona-ya approved these changes
To me this seems quite fine. This is a temporary migration that can be removed once all VMs had a reboot.

Upstreaming our reload script is a later, kinda unrelated task. Also nixpkgs currently doesn't need any stateDir handling based on e.g. state version as (as @laalsaas mentioned) it's deleted on every systemd service restart.

2024-09-04 15:32 UTC, ctheune approved these changes

2024-09-05 08:58 UTC, merged