Trigger cold reboots when RBD pool or CPU flags have changed from boot-time values
flyingcircusio/fc-nixos pull request #1124
Opened 2024-10-16 07:53 UTC by sysvinit

This change adds support to fc-agent for a new mechanism in fc.qemu which signals selected boot-time ENC parameters related to the KVM environment, similar to the existing qemu binary generation handling. The agent will compare the current ENC parameters with the boot-time parameters, and if changes are detected then a cold reboot will be scheduled in a maintenance window so the KVM host can carry out changes which require a restart of the qemu process.

PL-131857

@flyingcircusio/release-managers

## Release process

Impact:

Changelog:
- VMs will now automatically schedule reboots during maintenance when changes in CPU flags are requested or the VM disk is to be moved from HDD to SSD or vice versa (PL-131857).

### PR release workflow (internal)

- [x] PR has internal ticket
- [x] internal issue ID (PL-…) part of branch name
- [x] internal issue ID mentioned in PR description text
- [x] ticket is on Platform agile board
- [x] ticket state set to *Pull request ready*
- [x] if ticket is more urgent than within the next few days, directly contact a member of the Platform team

## Design notes

- [ ] Provide a feature toggle if the change might need to be adjusted/reverted quickly depending on context. Consider whether the default should be `on` or `off`. Example: rate limiting.
- [ ] All customer-facing features and (NixOS) options need to be discoverable from documentation. Add or update relevant documentation such that hosted and guided customers can understand it as well.

## Security implications

- [ ] [Security requirements](https://wiki.flyingcircus.io/System_Development_Guideline#Security_requirement_principles_and_testing) defined? (WHERE)
- [ ] Security requirements tested? (EVIDENCE)

2024-10-16 08:05 UTC, ctheune requested changes

2024-10-16 08:05 UTC, ctheune commented on pkgs/fc/agent/fc/maintenance/maintenance.py
> +ENC_PARAMETERS_FOR_COLD_REBOOT = ["cpu_model", "rbd_pool"]
As discussed: maintaining the parameters on the agent running within the VM is prone to us not being able to manage infrastructure aspects sufficiently independent from the guest agent. Meaning: if we decide that further parameters need to be able to trigger cold reboots, then we need to release updates to older platforms. Please let the inner agent just use whatever data is passed into the guest-properties file to make a decision for a cold boot.

2024-10-16 08:05 UTC, ctheune commented on pkgs/fc/agent/fc/maintenance/maintenance.py
> +        for key in ENC_PARAMETERS_FOR_COLD_REBOOT:
- newly added keys should likely trigger a reboot
- keys that go away maybe should not trigger a reboot?
- when making changes from the earlier comment this needs to exclude the binary generation OR decide that binary generation can also be downgraded and make the old/new style paths more separate (and then we can retire the old path in 24.11 or so)
- i think it's fine if we schedule gratuitous reboots to introduce this feature

2024-10-16 10:32 UTC, sysvinit commented
After further discussion we've decided to revise some of the logic in here, and instead of using ENC as the source of the desired state of the world, we should use an extra properties file fed into the VM by the qemu guest agent from the KVM layer. This means we're no longer limited to only comparing values inside ENC, and means we can detect new guest property values being added by the hypervisor at runtime which were not present at boot time.

2024-10-16 14:12 UTC, sysvinit commented on pkgs/fc/agent/fc/maintenance/maintenance.py
> +ENC_PARAMETERS_FOR_COLD_REBOOT = ["cpu_model", "rbd_pool"]
Fixed in [25e49b3](https://github.com/flyingcircusio/fc-nixos/pull/1124/commits/25e49b35f3b49b6e605f9fe2fcd7e8e3cf375a44)

2024-10-16 14:12 UTC, sysvinit commented on pkgs/fc/agent/fc/maintenance/maintenance.py
> +        for key in ENC_PARAMETERS_FOR_COLD_REBOOT:
Addressed in [25e49b3](https://github.com/flyingcircusio/fc-nixos/pull/1124/commits/25e49b35f3b49b6e605f9fe2fcd7e8e3cf375a44).

2024-10-18 09:09 UTC, ctheune approved these changes

2024-10-18 09:10 UTC, merged