rbbitmq: add sensu check
flyingcircusio/fc-nixos pull request #1201
Opened 2024-12-12 00:09 UTC by laalsaas

@flyingcircusio/release-managers

PL-132311
## Release process

- [x] Created changelog entry using `./changelog.sh`

## PR release workflow (internal)

- [x] PR has internal ticket
- [x] internal issue ID (PL-…) part of branch name
- [x] internal issue ID mentioned in PR description text
- [x] ticket is on Platform agile board
- [ ] ticket state set to *Pull request ready*
- [ ] if ticket is more urgent than within the next few days, directly contact a member of the Platform team

## Design notes

- [x] Provide a feature toggle if the change might need to be adjusted/reverted quickly depending on context. Consider whether the default should be `on` or `off`. Example: rate limiting.
- [ ] All customer-facing features and (NixOS) options need to be discoverable from documentation. Add or update relevant documentation such that hosted and guided customers can understand it as well.

## Security implications

- [ ] [Security requirements](https://wiki.flyingcircus.io/System_Development_Guideline#Security_requirement_principles_and_testing) defined? (WHERE)
- [ ] Security requirements tested? (EVIDENCE)

2024-12-12 22:30 UTC, osnyx requested changes
As long as it is not too complex, please add a corresponding test in our plattform rabbitmq tests. The other sensu checks are tested there as well.
We'd like to see changes in the output we're parsing here.

2024-12-12 22:30 UTC, osnyx commented on nixos/services/rabbitmq/default.nix
> +            ! /run/wrappers/bin/sudo -u rabbitmq ${pkgs.rabbitmq-server}/bin/rabbitmqctl list_feature_flags state stability |
It's a bit a matter of taste. but I'd like to avoid hard-coded absolute paths when introducing new things.
`sudo` is in PATH in the check env.

2024-12-13 19:57 UTC, laalsaas commented
I modified the test to make sure the check succeeds. I don't test for the check failing when rabbitmq is down, since this isn't a check for the "immediate status" of rabbitmq.

When rabbitmq is down, the rabbitmqctl command will fail. however, since the exit code of the entire statement is negated, the entire check will succeed. I don't think it is strictly neccessary, that the check fails, as explained above.

2024-12-17 13:35 UTC, merged

2024-12-17 13:38 UTC, osnyx commented on tests/rabbitmq.nix
> +    featureFlagCheck = "! sudo -u rabbitmq ${pkgs.rabbitmq-server}/bin/rabbitmqctl list_feature_flags state stability |${pkgs.gnugrep}/bin/grep stable | ${pkgs.gnugrep}/bin/grep  disabled";
This is basically code duplication, prone to diverting between test and actual check. We can instead pull in the actual code via the NixOS module system. I'll do that in a follow-up commit.