redis: add maxmemory option, add memoryPercentage option (fixes PL-115928)
flyingcircusio/fc-nixos pull request #282
Opened 2021-06-01 05:10 UTC by mkg20001

Fixes PL-115928

cc @dpausp 

Currently memoryPercentage has a default value (50%). Is that ok like that or should nothing be set by default?

2021-06-01 16:12 UTC, dpausp requested changes
50% as a default is ok, just some code-style changes requested :)

2021-06-01 16:12 UTC, dpausp commented on nixos/services/redis.nix
> +            maxmemory = config.flyingcircus.services.redis.maxmemory;
better use `memory = cfg.maxmemory;` (cfg defined at line 6) or even `inherit (cfg) maxmemory`;

2021-06-03 11:44 UTC, ctheune requested changes

2021-06-03 11:44 UTC, ctheune commented on nixos/services/redis.nix
> +        default = 50;
Talked to @zagy and looking at the existing instances we should go with an 80% default. @mkg20001

2021-06-08 13:01 UTC, merged