PL-129934 use upstream gitlab & jemalloc
flyingcircusio/fc-nixos pull request #302
Opened 2021-06-23 21:07 UTC by mkg20001

@flyingcircusio/release-managers

## Release process

Impact:

Changelog:
- Use GitLab from upstream (Note upstream PR still pending) to replace puma with unicorn for memory usage
- Re-add fc changes via gitlab/override.nix file
- Use jemalloc to further reduce memory usage

## Security implications

- [ ] [Security requirements](https://wiki.flyingcircus.io/System_Development_Guideline#Security_requirement_principles_and_testing) defined? (WHERE)
- [ ] Security requirements tested? (EVIDENCE)

2021-06-24 12:06 UTC, ctheune reviewed
@dpausp Please do a proper review and will fill in the security implications. I have made a note for myself to contact @chrschm and get @mkg20001 bootstrapped with our ISMS requirements.

2021-06-24 12:06 UTC, ctheune commented on nixos/roles/gitlab.nix
> +      /* extraGitLabRb = ''
Remove unused code, no need to keep this around.

2021-06-24 20:38 UTC, dpausp requested changes
nixos/services/gitlab/defaultUnicornConfig.rb can be removed

2021-06-24 20:38 UTC, dpausp commented on nixos/services/gitlab/default.nix
> +    ./override.nix
content from override.nix should be added to nixos/roles/gitlab.nix

2021-06-24 20:38 UTC, dpausp commented on nixos/services/default.nix
> +    ./gitlab/override.nix
content from override.nix should be added to nixos/roles/gitlab.nix

2021-07-08 09:59 UTC, dpausp requested changes
build breaks at the moment, please run the gitlab test after fixing and rebase

2021-07-08 09:59 UTC, dpausp commented on nixos/roles/gitlab.nix
> +    systemd.tmpfiles.rules = [
cfg is wrong here, cfg is defined as config.flyingcircus.roles.gitlab in the role

you want config.services.gitlab here

2021-07-09 10:46 UTC, merged