PL 129843 Nginx should be fully configurable via Nix code
flyingcircusio/fc-nixos pull request #340
Opened 2021-08-13 05:47 UTC by mkg20001

**NOTE: this is a draft for now. currently missing is the reload logic and there might be other undocumented changes (like the hashbucketsize option, which is currently PR'd upstream) - just comment if this PR removes anything from the module that isn't present in upstream but still needed**

upstream PRs:

- [x] https://github.com/NixOS/nixpkgs/pull/131962 listenAddresses
- [ ] https://github.com/NixOS/nixpkgs/pull/133585 serverNamesHashBucketMaxSize

@flyingcircusio/release-managers

## Release process

Impact:
- possible nginx restarts

Changelog:

## Security implications

- [ ] [Security requirements](https://wiki.flyingcircus.io/System_Development_Guideline#Security_requirement_principles_and_testing) defined? (WHERE)
- [ ] Security requirements tested? (EVIDENCE)

2021-08-24 21:24 UTC, dpausp requested changes
In the JSON config, setting an *SSL option automatically enables enableACME. We want to keep that. Doesn't work with the new NixOS options so the example config doesn't build anymore.

2021-08-24 21:24 UTC, dpausp commented on nixos/services/nginx/default.nix
> +    # default_type application/octet-stream;
Do we need this?

2021-08-24 21:28 UTC, mkg20001 commented on nixos/services/nginx/default.nix
> +    # default_type application/octet-stream;
Not really, removing

2021-08-24 21:31 UTC, mkg20001 commented
Indeed strange, as https://github.com/flyingcircusio/fc-nixos/pull/340/files#diff-f5fb9002fd859a9923715a59f5f83653e6baf9675b48013b8dc5bd567661ec75L73 should've enabled it.

2021-08-24 21:40 UTC, mkg20001 commented
![image](https://user-images.githubusercontent.com/7735145/130693651-aaddf70a-7765-4512-a2d4-399b18550b65.png)

Trying the example config from the README.txt results in acme jobs for the domain - couldn't reproduce

2021-08-24 21:54 UTC, mkg20001 commented
Tried with the nix version, that one indeed causes the problem. The issue is that `//` doesn't properly work with things from the module system, using lib.mkMerge causes other trouble (we have to override using mkForce, which means that if the user specifies enableACME themselves to false it will be overwritten, too)

2021-08-25 13:12 UTC, mkg20001 commented
Fixed. Now using the module system properly and overriding defaults for both enableACME and listenAddresses with what the fc function previously did.

2021-08-27 20:38 UTC, merged