Pl-129904 cgroup pressure information
flyingcircusio/fc-nixos pull request #453
Opened 2022-01-10 21:13 UTC by elikoga

@flyingcircusio/release-managers

## Release process

Impact:

Changelog:

## Security implications
None

- [x] [Security requirements](https://wiki.flyingcircus.io/System_Development_Guideline#Security_requirement_principles_and_testing) defined? (WHERE)
 - Exposes performance, not security relevant metrics to grafana dashboard
- [x] Security requirements tested? (EVIDENCE)
 - New metrics show up in grafana

2022-01-10 21:14 UTC, elikoga commented
Added option for regex

2022-01-13 13:09 UTC, dpausp requested changes
* the package name has a typo: `fc-telegraf-collet-psi` (from the previous PR)
*  commits should be squashed, have a longer commit message and contain the ticket ID from youtrack

2022-01-13 13:09 UTC, dpausp commented on nixos/services/telegraf/psi_input.nix
> +    flyingcircus.services.telegraf.psi_cgroup_regex = [ "^/system.slice$" "^/system.slice.*service$" "^/user.slice$" ];
camelCase for option names

2022-01-19 14:31 UTC, dpausp requested changes

2022-01-19 14:31 UTC, dpausp commented on nixos/services/telegraf/psi_input.nix
> +    flyingcircus.services.telegraf.psiCgroupRegex = [ "^/system.slice$" "^/system.slice.*service$" "^/user.slice$" ];
regex list should be empty by default, would produce too many metrics which our central statshost couldn't handle. Use the default regex as option example instead (and an option description would also be nice).

2022-01-26 13:18 UTC, merged