Pl-130311 fix k3s garbagecollect sudo tests
flyingcircusio/fc-nixos pull request #464
Opened 2022-01-17 23:30 UTC by elikoga

@flyingcircusio/release-managers

## Release process

Impact:

Changelog:

## Security implications

- [x] [Security requirements](https://wiki.flyingcircus.io/System_Development_Guideline#Security_requirement_principles_and_testing) defined? (WHERE)
  - existing tests are modified to un-fail 
- [x] Security requirements tested? (EVIDENCE)
  - tests run on hydra00

2022-01-17 23:31 UTC, elikoga commented
will squash once reviewed

2022-01-18 18:16 UTC, dpausp requested changes

2022-01-18 18:16 UTC, dpausp commented on tests/k3s/airgapped-k3s-images.py
> +        p = subprocess.run(["nix-prefetch-docker", f"{image['image']}", f"{image['tag']}"], capture_output=True)
use image['image'] as argument directly, string interpolation is a no-op here

2022-01-18 18:16 UTC, dpausp commented on tests/k3s/airgapped-k3s-images.py
> +        p = subprocess.run(["nix-prefetch-docker", f"{image['image']}", f"{image['tag']}"], capture_output=True)
`check=True` to catch exit codes > 0 here, `text=True` to decode utf8 (so you can append p.stdout directly in line 36)

2022-01-18 18:16 UTC, dpausp commented on tests/k3s/airgapped-k3s-images.py
> +        f.write(f"""[
writing in 3 parts (opening bracket, content, closing bracket) looks cleaner than a multiline string here

2022-01-20 12:19 UTC, merged