Switch development to NixOS 21.11
flyingcircusio/fc-nixos pull request #484
Opened 2022-02-17 13:04 UTC by dpausp

@flyingcircusio/release-managers

### Significant breaking changes

* haproxy doesn't support `log localhost` anymore, use `log 127.0.0.1` instead
* PHP 5.6 is EOL for a long time and has been removed
* Postgresql 9.6 is EOL and has been removed
* OpenSSH 8.8 default settings break connections to old SSH daemons as ssh-rsa host keys and ssh-rsa public keys that were signed with SHA-1 are disabled now

### Possible problems

* iptables now uses nf_tables backend. We experienced problems when mixing legacy and new firewall rules that were gone after a reboot.

### Significant package updates

* bash now defaults to major version 5.
* python3 is now python39
* The varnish package was upgraded from 6.3.x to 7.x.
* k3s: 1.21 -> 1.22
* docker: 20.10.7 -> 20.10.9
* elasticsearch: 6.8.3 -> 6.8.21
* erlang: 23.3.4.5 -> 24.1.6
* docker-compose: 1.28.6 -> 1.29.2, 2.0.1
* git:  2.31.1 -> 2.33.1
* glibc: 2.32-54 ->  2.33-117
* kubernetes-helm: 3.5.4 -> 3.8.0
* imagemagick: 7.1.0-19 -> 7.1.0-24
* inetutils: 1.9.4 -> 2.2
* linux: 5.10.88 -> 5.10.99
* mailutils: 3.12 -> 3.13
* openssl: 1.1.1l -> 1.1.1m
* postfix: 3.6.0 -> 3.6.4
* rabbitmq: 3.8.9 -> 3.9.8
* sudo: 1.9.7 -> 1.9.7p2
* telegraf: 1.18.1 -> 1.20.3
* util-linux: 2.36.2 -> 2.37.3
* varnish: 6.3.2 -> 7.0.2
* systemd: 247 -> 249

## Other notable changes

* The setting services.openssh.logLevel "VERBOSE" "INFO". This brings NixOS in line with upstream and other Linux distributions, and reduces log spam on servers due to bruteforcing botnets.

## Release process

Impact:

Changelog:

(announce in changelog that there's a new platform version and main development has switched to it)

## Security implications

- [x] [Security requirements](https://wiki.flyingcircus.io/System_Development_Guideline#Security_requirement_principles_and_testing) defined? (WHERE)
  - we want to follow NixOS releases to get upstream security fixes
  - look at release notes to find new security implications and possible breakage when upgrading systems
- [x] Security requirements tested? (EVIDENCE)
  - reviewed NixOS release notes for breaking changes, security-related and other significant changes 
  - all tests are green, various VMs already running on 21.11 without problems

2022-02-17 13:39 UTC, ctheune requested changes
see comments

2022-02-17 13:39 UTC, ctheune commented on nixos/platform/static.nix
>        sensuapi = 31002;
if sensu server is gone then the api and uchiwa need to go away, too

2022-02-17 13:39 UTC, ctheune commented on nixos/services/postgresql.nix
> +            The major version of PostgreSQL to use (10, 11, 12, 13).
14 is missing here or make it more explicit that those are examples

2022-02-17 13:39 UTC, ctheune commented on pkgs/overlay.nix
> +  #grub2_full = super.callPackage ./grub/2.0x.nix { };
can be removed completely

2022-02-17 13:39 UTC, ctheune commented on release/default.nix
>      "gitlab"
i think gitlab can be removed here

2022-02-17 13:39 UTC, ctheune commented on release/default.nix
> +    "ceph"
remove here so it becomes tested again when we enable the package

2022-02-17 13:39 UTC, ctheune commented on tests/default.nix
> -  sensu = callTest ./sensu.nix {};
can we ensure that we have a test cover that the client still works?

2022-02-22 14:14 UTC, dpausp commented on tests/default.nix
> -  sensu = callTest ./sensu.nix {};
added a new test that tests sensu client in isolation (just a local rabbitmq to connect to)

2022-02-23 12:55 UTC, merged