Pl 130693 ceph luminous
flyingcircusio/fc-nixos pull request #565
Opened 2022-06-24 15:43 UTC by osnyx

@flyingcircusio/release-managers

## Release process

Impact:

Changelog:

## Security implications

- [ ] [Security requirements](https://wiki.flyingcircus.io/System_Development_Guideline#Security_requirement_principles_and_testing) defined? (WHERE)
- [ ] Security requirements tested? (EVIDENCE)

2022-09-08 10:03 UTC, ctheune requested changes

2022-09-08 10:03 UTC, ctheune commented on pkgs/overlay.nix
> +    # TODO: try newer boost versions
not needed. remove todo marker.

2022-09-08 10:03 UTC, ctheune commented on pkgs/overlay.nix
> +        pythonImportsCheckPhase = ''
I think this can be simplified.

2022-09-08 10:03 UTC, ctheune commented on pkgs/fc/ceph/default.nix
> +  # FIXME: only temporary
well, fix it then ;)

2022-09-08 10:03 UTC, ctheune commented on pkgs/fc/ceph/src/fc/ceph/main.py
> +# FIXME: move to OSD module exported constants
please check

2022-09-08 10:03 UTC, ctheune commented on pkgs/fc/ceph/src/fc/ceph/main.py
> +        # FIXME: do I explicitly need to add the choices to the help text?
check

2022-09-08 10:03 UTC, ctheune commented on pkgs/fc/ceph/src/fc/ceph/subsystems.py
> +class VersionedSubsystem(object):
this seems to  be a duplicate of fc.ceph.VersionedSubsystems. I think this file can just go away.

2022-09-08 10:03 UTC, ctheune commented on nixos/roles/backyserver.nix
> +  ceph_common = import ./ceph/ceph-common.nix { inherit lib pkgs; };
please refactor to leverage fclib.ceph instead of introducing a new pattern

2022-09-08 10:03 UTC, ctheune commented on nixos/roles/ceph/osd.nix
> +          # we currently have (too) many PGs in our pools, make sure the clsuter still
typo

2022-09-08 10:03 UTC, ctheune commented on tests/default.nix
>    kvm_host = callTest ./kvm_host.nix {};
Suggestin: rename to kvm_host_jewel-ceph-server-jewel and avoid a version-less alias

2022-09-19 13:05 UTC, dpausp requested changes

2022-09-19 13:05 UTC, dpausp commented on nixos/roles/backyserver.nix
> +  backy_rbd_versioned = cephReleaseName: {
style: indentation, camelCase

2022-09-19 13:05 UTC, dpausp commented on nixos/roles/ceph/osd.nix
> +        # FIXME: the module uses the `rbd` binary. While it'd be safer to handle it's
remove FIXME

2022-09-19 16:37 UTC, dpausp approved these changes

2022-09-19 16:37 UTC, merged