mailserver: WIP allow building on devhost
flyingcircusio/fc-nixos pull request #580
Opened 2022-07-28 12:09 UTC by dpausp

@flyingcircusio/release-managers

## Release process

Impact:

Changelog:

## Security implications

- [ ] [Security requirements](https://wiki.flyingcircus.io/System_Development_Guideline#Security_requirement_principles_and_testing) defined? (WHERE)
- [ ] Security requirements tested? (EVIDENCE)

2022-07-28 14:00 UTC, ctheune requested changes

2022-07-28 14:00 UTC, ctheune commented on nixos/services/mail/default.nix
> +    concatMapStringsSep "\n"
I would rather recommend to set xyz@example.com for the synthetic human and service user in containers.

2022-07-28 14:00 UTC, ctheune commented on nixos/services/mail/default.nix
> +  feAddresses =
Hmmhmnhmnhm. I'd prefer the build to fail if running without FE. Unsure how to properly fake this in our container environment.

2022-07-28 14:00 UTC, ctheune commented on nixos/services/mail/default.nix
> +  feAddresses =
One option: make this an option in our role, use FE as default and override via container.nix

2022-10-06 18:37 UTC, dpausp commented on nixos/services/mail/default.nix
> +  feAddresses =
All other parts of the role/service check if FE is available and use SRV or nothing instead if there is no frontend. The new option is the better approach here.

2022-10-10 09:25 UTC, merged