Pre fc 22.11
flyingcircusio/fc-nixos pull request #666
Opened 2023-02-20 12:34 UTC by dpausp

@flyingcircusio/release-managers

## Release process

Impact:

Changelog:

## Security implications

- [ ] [Security requirements](https://wiki.flyingcircus.io/System_Development_Guideline#Security_requirement_principles_and_testing) defined? (WHERE)
- [ ] Security requirements tested? (EVIDENCE)

2023-02-20 13:47 UTC, dpausp reviewed
some changes

2023-02-20 13:47 UTC, dpausp commented on tests/lamp/vm-test.nix
> +  #extraPythonPackages = p: with p; [ types-setuptools ];
does this work now? If not, add a comment about what's happening

2023-02-20 13:47 UTC, dpausp commented on nixos/roles/statshost/default.nix
> +          "auth.ldap" = {
squash with previous grafana commit

2023-02-20 13:47 UTC, dpausp commented on tests/default.nix
> +  # XXX: fails at the tideways check since 9d6bb722c1527a154726a4458ad7d5a865d7eea7
does this still fail?

2023-02-20 13:47 UTC, dpausp commented on nixos/platform/agent.nix
> +    #compdef fc-slurm
fc-slurm doesn't exist yet :)

2023-02-20 13:47 UTC, dpausp commented on nixos/platform/default.nix
> +      default = null;
readonly?

2023-02-20 23:01 UTC, dpausp commented on tests/default.nix
> +  # XXX: fails at the tideways check since 9d6bb722c1527a154726a4458ad7d5a865d7eea7
yes, the daemon runs but the PHP module doesn't appear in phpinfo

2023-02-21 12:18 UTC, dpausp commented on tests/lamp/vm-test.nix
> +  #extraPythonPackages = p: with p; [ types-setuptools ];
changed: using `Version` from `packaging.version` works with type-checking.

2023-02-22 17:09 UTC, dpausp commented on tests/default.nix
> +  # XXX: fails at the tideways check since 9d6bb722c1527a154726a4458ad7d5a865d7eea7
it's fixed now

2023-02-22 17:15 UTC, osnyx requested changes

2023-02-22 17:15 UTC, osnyx commented on nixos/platform/default.nix
> +        This is the same as the `rgw.local` entry in `/etc/hosts`. Set if the
foo

2023-02-22 17:15 UTC, osnyx commented on nixos/platform/default.nix
> +        This is the same as the `rgw.local` entry in `/etc/hosts`. Set if the
```suggestion
        This is the same as the `rgw.local` entry in `/etc/hosts`. Value is set if the
```

Clarify that *Set* describes the state of the option value, not the verb/ action of the possibility that you can/ should set it for virtual machines.

If we decide to mark it as read-only, possibly even extend to *Value is set by the platform if…*

2023-02-22 21:03 UTC, osnyx approved these changes

2023-02-23 14:03 UTC, dpausp commented
removed graylog/loghost after review

2023-02-23 14:30 UTC, osnyx approved these changes

2023-02-27 10:57 UTC, dpausp commented
Merging after a team review of the important and security-relevant aspects mentioned in the PR message.

2023-02-27 13:49 UTC, merged