Improve Kubernetes monitoring and telemetry
flyingcircusio/fc-nixos pull request #725
Opened 2023-06-07 07:18 UTC by sysvinit

WIP. Please check the individual commit messages for detailed commentary.

PL-131009

@flyingcircusio/release-managers

## Release process

Impact: internal

Changelog:

## Security implications

- [ ] [Security requirements](https://wiki.flyingcircus.io/System_Development_Guideline#Security_requirement_principles_and_testing) defined? (WHERE)
- [ ] Security requirements tested? (EVIDENCE)

2023-07-11 09:42 UTC, dpausp requested changes
Looks great overall, just some cosmetic changes. Please squash some commits, we usually have one per PR but a few are also fine where it makes sense.

2023-07-11 09:42 UTC, dpausp commented on nixos/roles/k3s/server.nix
> +      echo 'cloud not read secret token' 2>&1
cloud -> could

2023-07-11 09:42 UTC, dpausp commented on nixos/roles/k3s/server.nix
> +    ${pkgs.kubectl}/bin/kubectl get -n kube-system -o jsonpath='{.data.token}' secret "$secret" | \
This seems redundant, we already have `$tokendir/$user.tmp` created by the code above?

2023-07-12 12:51 UTC, sysvinit commented on nixos/roles/k3s/server.nix
> +      echo 'cloud not read secret token' 2>&1
Fixed in [15c9e05](https://github.com/flyingcircusio/fc-nixos/pull/725/commits/15c9e059c359fac41adef953ddd7a0d8a410ae1c)

2023-07-12 12:51 UTC, sysvinit commented on nixos/roles/k3s/server.nix
> +    ${pkgs.kubectl}/bin/kubectl get -n kube-system -o jsonpath='{.data.token}' secret "$secret" | \
That's dead code which wasn't properly removed when I refactored that script, oops. Fixed in [15c9e05](https://github.com/flyingcircusio/fc-nixos/pull/725/commits/15c9e059c359fac41adef953ddd7a0d8a410ae1c).

2023-07-12 12:52 UTC, sysvinit commented
> Please squash some commits, we usually have one per PR but a few are also fine where it makes sense.

Ack, squash incoming.

2023-07-12 22:57 UTC, merged