Bring back old MongoDB roles 3.4-4.2 for upgrades
flyingcircusio/fc-nixos pull request #874
Opened 2024-01-04 09:52 UTC by dpausp

@flyingcircusio/release-managers

## Release process

Impact:

Changelog:

* mongodb roles from version 3.2 to 4.2 are now available again to allow upgrades of older machines (PL-131229).

## Security implications

- [x] [Security requirements](https://wiki.flyingcircus.io/System_Development_Guideline#Security_requirement_principles_and_testing) defined? (WHERE)
  - nothing new, we bring back legacy MongoDB versions to be able to upgrade outdated VMs. Packages are taken from older platform versions and the role/service is the same as on 23.05 with added compatibility code from older platform versions.
- [x] Security requirements tested? (EVIDENCE)
   - checked on a test VM that upgrades with mongodb32 from 15.09 up to 23.11 work as expected (with 19.03 and 20.09 as intermediary steps, role has to be deactivated on 20.09)

2024-01-15 11:41 UTC, dpausp commented on doc/src/mongodb.md
> +As a replacement, we are working on [FerretDB](https://www.ferretdb.com/)
we actually support FerretDB now :)

2024-01-15 11:41 UTC, dpausp commented on nixos/roles/mongodb.nix
> +      mongodb-3_2 = /nix/store/hjv1grfh9s5jhmk0fd0pdcxphg0j76k8-mongodb-3.2.12;
add a comment: where are this packages from?

2024-01-15 11:41 UTC, dpausp commented on release/default.nix
> +    "mongodb_3_2"
can be removed, they are defined in the service directly now and not in the overlay

2024-01-15 11:41 UTC, osnyx requested changes

2024-01-15 11:41 UTC, osnyx commented on release/default.nix
>    excludedPkgNames = [
can be removed, the used packages have been in-lined

2024-01-15 11:41 UTC, osnyx commented on doc/src/mongodb.md
> +As a replacement, we are working on [FerretDB](https://www.ferretdb.com/)
We've already implemented the first beta release of a ferretdb role, consider linking to that.

2024-01-16 08:37 UTC, osnyx approved these changes

2024-01-16 08:37 UTC, merged