[PL-132155] roles/mailserver: require an actual url as imprintUrl
flyingcircusio/fc-nixos pull request #905
Opened 2024-02-07 13:32 UTC by Ma27

Even though the option was called `imprintUrl` the protocol scheme was prepended unconditionally. This means when defining an `imprintUrl` like

    https://example.org/impressum

a redirect to `https://https//example.org/impressum` will be issued which is pretty unintuitive.

Since the option claims to accept a URL I decided to change its semantics like this:

* A URL is expected now (as long as it's accepted by the `return` clause of nginx).

* For backwards-compatibility, a "URL" w/o a scheme (i.e. `example.com`) is also accepted. This behavior is deprecated however and gives the following warning at evaluation time:

      trace: warning: Specifying flyingcircus.roles.mailserver.imprintUrl without a protocol scheme is deprecated. Add https:// to the declaration (i.e. "example.com" -> "https://example.com") to get rid of this warning.

  We could drop the old behavior after e.g. the first platform release with NixOS 24.11. When doing that, the `apply` expression should be dropped and the validation should be done by using `nullOr (strMatching "")` instead.

A test-case to the integration test of the mailserver role was added which ensures that the redirect declared by `imprintUrl` works fine.

@flyingcircusio/release-managers

## Release process

Impact:

Changelog:
* mailserver: `imprintUrl` now accepts a protocol scheme. Specifying this option without a protocol scheme still works as before, but is deprecated and will raise a warning (PL-132155)

### PR release workflow (internal)

- [x] PR has internal ticket
- [x] internal issue ID (PL-…) part of branch name
- [x] internal issue ID mentioned in PR description text
- [x] ticket is on Platform agile board
- [ ] ticket state set to *Pull request ready*
- [ ] if ticket is more urgent than within the next few days, directly contact a member of the Platform team

## Security implications

- [x] [Security requirements](https://wiki.flyingcircus.io/System_Development_Guideline#Security_requirement_principles_and_testing) defined? (WHERE)
    - Reduce the chance of human error: a misconfigured redirect to the imprint is accepted by the module and may be unnoticed. However, the lack of an imprint may violate the ToS of other mail providers which potentially causes the mailserver to be banned by other providers.
- [x] Security requirements tested? (EVIDENCE)
    - Additional testcase in the integration test ensures that an imprintUrl with a protocol scheme gets properly redirected.
    - Manually verified that an imprintUrl without a protocol scheme gets properly redirected and gives a deprecation warning.

2024-02-07 18:02 UTC, osnyx requested changes
Looks good overall, just a small nitpick.

2024-02-07 18:02 UTC, osnyx commented on tests/mail/default.nix
> +      imprint_request_headers = client.succeed("curl mail.example.local -I | xargs -I {} echo {}").split('\n')
```suggestion
      imprint_request_headers = client.succeed("curl http://mail.example.local -I | xargs -I {} echo {}").split('\n')
```

Talking about protocol specifications, this makes it a bit more clear, also in case curl defaults ever change.

2024-02-07 18:02 UTC, osnyx commented on tests/mail/default.nix
> +      imprint_request_headers = client.succeed("curl mail.example.local -I | xargs -I {} echo {}").split('\n')
I am also not fully sure why the xargs construction is necessary, doesn't `curl -I` already print headers line by line to stdout by itself?

2024-02-08 09:35 UTC, Ma27 commented on tests/mail/default.nix
> +      imprint_request_headers = client.succeed("curl mail.example.local -I | xargs -I {} echo {}").split('\n')
> I am also not fully sure why the xargs construction is necessary, doesn't curl -I already print headers line by line to stdout by itself?

curl doesn't print terminal escape codes when piping it to another command and that way I don't have to bother about dealing with them. If you know a better way (didn't find a useful option in the man page and NO_COLOR=1 doesn't work either), let me know :)

2024-02-08 22:41 UTC, osnyx commented on tests/mail/default.nix
> +      imprint_request_headers = client.succeed("curl mail.example.local -I | xargs -I {} echo {}").split('\n')
As I assume you've done some research and I don't know one either from the top of my head, I'm fine with this hack.

2024-02-08 22:41 UTC, osnyx approved these changes

2024-02-08 22:41 UTC, merged

2024-02-08 22:46 UTC, osnyx commented on tests/mail/default.nix
> +      imprint_request_headers = client.succeed("curl mail.example.local -I | xargs -I {} echo {}").split('\n')
I guess piping to `cat` would've worked as well though.