[21.05] FDE: admin fingerprint
flyingcircusio/fc-nixos pull request #966
Opened 2024-04-11 22:31 UTC by osnyx

@flyingcircusio/release-managers

Compute and display a hash fingerprint of the LUKS admin passphrase entered and store it alongside the key file on the keystore USB stick.
This helps discovering accidentally wrong keys entered into a system and debug unknown/ corrupted passphrase states.

Missing fingerprints or mismatches are displayed and resolved interactively.

This PR does __not__ yet include tooling subcommands of `fc-luks` for working with fingerprints, but due to the in-band interactive conflict resolution process this state is already fine to be rolled out to production without such tools.

PL-131325

## Release process

Impact: internal

Changelog:

### PR release workflow (internal)

- [x] PR has internal ticket
- [x] internal issue ID (PL-…) part of branch name
- [x] internal issue ID mentioned in PR description text
- [x] ticket is on Platform agile board
- [x] ticket state set to *Pull request ready*
- [x] if ticket is more urgent than within the next few days, directly contact a member of the Platform team

## Design notes

- [x] Provide a feature toggle if the change might need to be adjusted/reverted quickly depending on context. Consider whether the default should be `on` or `off`. Example: rate limiting.
- [x] All customer-facing features and (NixOS) options need to be discoverable from documentation. Add or update relevant documentation such that hosted and guided customers can understand it as well.

## Security implications

- [x] [Security requirements](https://wiki.flyingcircus.io/System_Development_Guideline#Security_requirement_principles_and_testing) defined? (WHERE)
  - [x] improve handling and discoverability of passphrase mismatches for operators
  - [x] extend automated tests
  - [x] fine-grained unit tests for all common input flows
  - [x] must not introduce known regressions
  - [x] must work on existing encrypted hosts and update them with a fingerprint
- [ ] Security requirements tested? (EVIDENCE)
  - [ ] automated tests pass
  - [x] extended unit tests
  - [x] manually tested on patty
  - [x] manually initialised the fingerprint on patty while maintaining the same passphrase

2024-05-03 08:20 UTC, ctheune requested changes
overall: very good, the one thing about handling external headers vs. mass operations needs an alternative solution

2024-05-03 08:20 UTC, ctheune commented on pkgs/fc/ceph/src/fc/ceph/luks/__init__.py
> +    class Fingerprint(bytes):
move to top level scope

2024-05-03 08:20 UTC, ctheune commented on pkgs/fc/ceph/src/fc/ceph/luks/__init__.py
> +            *args,
your formatter ignored the `fmt: off` directives

2024-05-03 08:20 UTC, ctheune commented on pkgs/fc/ceph/src/fc/ceph/luks/manage.py
> +            this_header = header
we shouldn't intermingle giving a specific luks header to a multi-volume operation

2024-05-03 08:20 UTC, ctheune commented on pkgs/fc/ceph/src/fc/ceph/luks/__init__.py
> +    __admin_key: Optional[bytes] = None
this is unused, or rather should be __admin_key_for_input

2024-05-03 18:56 UTC, osnyx commented on pkgs/fc/ceph/src/fc/ceph/luks/__init__.py
> +            *args,
No, *someone's* formatter did ;)

2024-05-06 09:25 UTC, ctheune approved these changes

2024-05-06 09:25 UTC, merged