ceph: clean up mon/mgr/rgw dependencies
flyingcircusio/fc-nixos pull request #995
Opened 2024-05-03 06:55 UTC by ctheune

Required turning the mon and mgr units into simple units.

Fixes PL-132473

@flyingcircusio/release-managers

## Release process

Impact:

n/a

Changelog:

n/a

### PR release workflow (internal)

- [x] PR has internal ticket
- [x] internal issue ID (PL-…) part of branch name
- [x] internal issue ID mentioned in PR description text
- [x] ticket is on Platform agile board
- [x] ticket state set to *Pull request ready*
- [ ] if ticket is more urgent than within the next few days, directly contact a member of the Platform team

## Design notes

- [x] Provide a feature toggle if the change might need to be adjusted/reverted quickly depending on context. Consider whether the default should be `on` or `off`. Example: rate limiting.
- [x] All customer-facing features and (NixOS) options need to be discoverable from documentation. Add or update relevant documentation such that hosted and guided customers can understand it as well.

## Security implications

- [x] [Security requirements](https://wiki.flyingcircus.io/System_Development_Guideline#Security_requirement_principles_and_testing) defined? (WHERE)

Limit unnecessary downtimes.

- [x] Security requirements tested? (EVIDENCE)

Manually tested on cartman06, relying on existing test suite.

2024-05-03 12:28 UTC, osnyx requested changes, later dismissed
LGTM in general, but ruff has again messed up the formatting. Please adjust.

2024-05-03 12:28 UTC, osnyx commented on pkgs/fc/ceph/src/fc/ceph/mon/nautilus.py
> +                "-n",
formatting is broken

2024-05-03 12:28 UTC, osnyx commented on pkgs/fc/ceph/src/fc/ceph/mon/nautilus.py
> +                "--cap",
same

2024-05-03 12:28 UTC, osnyx commented on pkgs/fc/ceph/src/fc/ceph/mon/nautilus.py
> +            "-i",
same

2024-05-03 12:28 UTC, osnyx commented on pkgs/fc/ceph/src/fc/ceph/osd/nautilus.py
> +            "-S",
formatting

2024-05-03 12:28 UTC, osnyx commented on pkgs/fc/ceph/src/fc/ceph/osd/nautilus.py
> +            "auth",
formatting

2024-05-03 12:28 UTC, osnyx commented on pkgs/fc/ceph/src/fc/ceph/osd/nautilus.py
> +                    "OSD not safe to destroy:",
formatting

2024-05-03 12:28 UTC, osnyx commented on pkgs/fc/ceph/src/fc/ceph/osd/nautilus.py
> +                    "OSD not okay to stop:",
formatting

2024-05-03 12:28 UTC, osnyx commented on pkgs/fc/ceph/src/fc/ceph/osd/nautilus.py
> +            "-i",
formatting

2024-05-03 12:28 UTC, osnyx commented on pkgs/fc/ceph/src/fc/ceph/osd/nautilus.py
> +            "-i",
formatting

2024-05-07 10:46 UTC, dpausp approved these changes
based on the review by osnyx: the formatting errors have been fixed, so LGTM

2024-05-07 10:46 UTC, merged